// quotes.js — Spill Joy encouragement quotes
// 72 quotes. Every entry is displayed at random on the result screen.

const QUOTES = [
  "You've handled worse Tuesdays than this one.",
  "That thing you're overthinking? It's going to work out fine.",
  "Take the nap. Drink the water. Send the text tomorrow.",
  "You're doing better than you think you are — check your receipts.",
  "It's okay to not have it all figured out by 3pm.",
  "Small steps still move you forward. You're not stuck.",
  "The thing you're worrying about probably won't happen. And if it does, you'll handle it.",
  "You don't need to earn your rest. You already deserve it.",
  "Someone is glad you exist today, even if they haven't texted yet.",
  "Your best is allowed to look different on different days.",
  "That idea you have? It's not stupid. Explore it.",
  "You're allowed to outgrow things that used to fit you.",
  "The email can wait. Your peace can't.",
  "You've survived 100% of your hard days. That's a pretty good track record.",
  "It's not lazy to need a break. It's human.",
  "Whatever you're building is taking longer than you wanted, but it's still growing.",
  "You don't have to be perfect to be worth knowing.",
  "Sometimes the most productive thing you can do is nothing for a while.",
  "Your gut feeling about that situation? Trust it.",
  "Tomorrow is a new shot at this. Tonight, just breathe.",
  "You're not failing; you're just in the messy middle of figuring it out.",
  "The project doesn't need to be perfect; it needs to be done.",
  "Your pace is your pace. Stop looking at everyone else's timeline.",
  "Your \"good enough\" is probably someone else's \"how do they do it?\"",
  "It's not procrastination if you're letting an idea marinate.",
  "You can be grateful for the opportunity and tired from it at the same time.",
  "The thing you're putting off? It'll take 12 minutes. Just start.",
  "You don't need to have the solution right now. Asking questions counts.",
  "You're allowed to outgrow friends without it being a betrayal.",
  "It's brave to say \"I'm struggling\" instead of \"I'm fine.\"",
  "The version of you that needs help is just as worthy as the version that doesn't.",
  "You're not running out of ideas; you're just tired. Rest refills the well.",
  "Inspiration comes when you start moving, not when you're waiting to move.",
  "Today doesn't get to define your whole month.",
  "Sometimes the win is just getting to bedtime. That counts.",
  "You're not lazy; you're depleted. There's a difference.",
  "It's okay if the only thing you did today was survive it.",
  "The guilt you feel about resting is just noise. Ignore it.",
  "This feeling has an expiration date, even if you can't see it yet.",
  "You don't have to solve everything right now. Just get through the hour.",
  "It's okay to not be grateful for the lesson while you're learning it.",
  "Your nervous system is overwhelmed, not broken. Be gentle with it.",
  "Some days you just need to exist horizontally. Do it without apology.",
  "The world will keep turning if you log off for a day.",
  "You don't have to turn this pain into poetry. You can just feel it.",
  "It's okay to cry about something small when the big things are too heavy.",
  "You're not behind; you're just taking the scenic route through this mess.",
  "Sometimes the bravest thing is admitting today is not your day.",
  "Your worth isn't tied to your productivity. Write that on your mirror.",
  "It's okay to ask for help even if you \"should\" be able to handle it.",
  "This won't be the hardest thing you ever do. You've got proof you can survive.",
  "Tomorrow is a reset button. For now, just get there.",
  "Breathe. That's enough for right now.",
  "You're making more progress than you can see.",
  "It's okay to want more and appreciate what you have.",
  "The hard part is usually just starting. You're past that now.",
  "You're exactly where you need to be to get where you're going.",
  "Don't rush the thing that's trying to grow.",
  "You don't have to explain yourself today.",
  "Sometimes the bravest thing is just showing up.",
  "Let it be messy for a while. It won't always be.",
  "You're doing better than your worries say you are.",
  "The answer you're looking for is closer than you think.",
  "It's fine to not have a plan for once.",
  "You're allowed to take up room. All of it.",
  "Whatever you're feeling is valid, even if it's inconvenient.",
  "You don't have to earn the good thing that's coming.",
  "Rest is part of the process, not a pause from it.",
  "You've survived enough to know you can handle this.",
  "It's okay if today looks different than you expected.",
  "Trust yourself a little more. You've got good instincts.",
  "This feeling won't last forever. Nothing does, and that's the good news."
];

window.QUOTES = QUOTES;
